name: wx天气预报推送

on:
  schedule:
    # # UTC 0:00 → 北京 8:00（非预期的早7点）
    - cron : '0 0 * * *'
    # 北京时间 22:05（对应 UTC 14:05）
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Daily Weather Report

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install wechatpy lunardate requests

    - name: Run weather script
      run: python main.py
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        TEMPLATE_ID_DAY: ${{ secrets.TEMPLATE_ID_DAY }}
        TEMPLATE_ID_NIGHT: ${{ secrets.TEMPLATE_ID_NIGHT }}
        USER_IDS: ${{ secrets.USER_IDS }}
        START_DATE: ${{ secrets.START_DATE }}
        NAME: ${{ secrets.NAME }}
        BIRTHDAY: ${{ secrets.BIRTHDAY }}
        CITY: ${{ secrets.CITY }}
